version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 64542:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  comptasup_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comptasup_api
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached  # Utilisation de :cached pour optimiser les performances
      - /var/www/html/vendor    # Volume Docker interne pour éviter de monter vendor
      - /var/www/html/node_modules # Volume interne pour éviter de monter node_modules
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: comptasup_api
      DB_USERNAME: root
      DB_PASSWORD: 1234
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "64543:80"
    depends_on:
      - comptasup_api

  apidoc :
    build:
      context: .
      dockerfile: Dockerfile.express  # Spécifiez votre Dockerfile Express
    container_name: apidoc
    ports:
      - "64545:64545"  # Mappez le port 64545 pour accéder à l'application Express
    volumes:
      - .:/app  # Assurez-vous que le fichier index.html et le code Express sont dans le répertoire monté.

volumes:
  mysql_data: {}
